from setuptools import setup
from glob import glob

"""
The below docstrings and comments were generated by GPT-4o on 4/3/25 @ 12:00pm

This script sets up the Multiple Sclerosis Research project for distribution.
It specifies metadata, dependencies, entry points, and includes both code modules and data files.
Run `pip install .` from the root directory to install the package locally.
"""
setup(
    name="multiple-sclerosis-research",  # Project name
    version="1.0.0",                     # Initial release version
    author="Tal Erez",                   # Author name
    author_email="tal.erez@duke.edu",    # Author contact
    description="Multiple Sclerosis Research",  # Short project description
    url="https://github.com/notthattal/multiple-sclerosis-research",  # Project homepage

    # Python modules to include, located inside the 'scripts' directory
    py_modules=[
        "data_preprocessing",
        "deep_learning_model",
        "naive_model",
        "traditional_model",
        "train_models"
    ],
    package_dir={'': 'scripts'},  # Tells setuptools to find modules in 'scripts/'

    # Required packages with fixed versions for reproducibility
    install_requires=[
        "numpy==2.0.2",
        "pandas==2.2.3",
        "scikit-learn==1.6.1",
        "torch==2.6.0",
        "scipy==1.13.1",
    ],

    # CLI entry point: allows running `train-models` in terminal
    entry_points={
        "console_scripts": [
            "train-models=train_models:main",
        ],
    },

    python_requires=">=3.9",  # Minimum Python version requirement

    include_package_data=True,  # Include non-code files specified in MANIFEST or setup

    # Include external data files with the installation
    data_files=[
        ('data/raw_data/MSGaits', glob('data/raw_data/MSGaits/*')),
        ('data/raw_data/NormativeGaits', glob('data/raw_data/NormativeGaits/*')),
        ('data/processed_data', glob('data/processed_data/*'))
    ],
)